### ISSUE TITLE
Grafana CLI version 7.0.3  did not support consul !?

### ISSUE THREAD

**Issue by BusterZr** [sbueringer/grafana-consul-datasource#11]
I upgrade the grafana-server to 7.0.3,but datasource consul cann not be used as usual.anybody can help me ?   QAQ
![image](https://user-images.githubusercontent.com/38774283/83724436-da77fa80-a672-11ea-8a9c-f69b52ed91f6.png)

![image](https://user-images.githubusercontent.com/38774283/83724614-29be2b00-a673-11ea-99d5-bf246789b95b.png)
![image](https://user-images.githubusercontent.com/38774283/83724628-2e82df00-a673-11ea-901d-150b4854788c.png)

**Comment by sbueringer** [comment]
@BusterZr I'll take a look. Still using Grafana 6 right now

**Comment by sbueringer** [comment]
@BusterZr Grafana 7 doesn't run unsigned plugins per default. So one solution would be to add the following to your grafana.ini:

```
[plugins]                                                                                                                                                                                                                                                                 
allow_loading_unsigned_plugins = "sbueringer-consul-datasource" 
```

Not sure why it didn't show up in your log, but I found this
* without the setting:
```
t=2020-06-11T07:59:26+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"sbueringer-consul-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/grafana-consul-datasource-v0.1.5/dist
t
```
* with the setting
```
t=2020-06-11T08:02:16+0000 lvl=warn msg="Running an unsigned backend plugin" logger=plugins pluginID=sbueringer-consul-datasource pluginDir=/var/lib/grafana/plugins/grafana-consul-datasource-v0.1.5/dist
```

**Comment by igorid70** [comment]
Hi
I added to configuration: 
allow_loading_unsigned_plugins = "sbueringer-consul-datasource"
and indeed the error msg="Failed to load plugin" logger=plugins error="plugin \"sbueringer-consul-datasource\" is unsigned" is gone, however after the restart all users (beside the admin) and dashboards disappeared plus each operation (like selecting 'users' or 'data sources' in configuration menu generates "Permission denied" messages

![image](https://user-images.githubusercontent.com/66210968/84883284-03e44d80-b099-11ea-8ced-8ecddec8d991.png)

though consul data source is added (I still did not try to configure it as it seems the entire grafana setup is messed up after adding the plugin)

![image](https://user-images.githubusercontent.com/66210968/84883437-2fffce80-b099-11ea-8195-7fec8ea7e1ce.png)

**Comment by sbueringer** [comment]
Hm strange. We're running our Grafana 7 (which also uses Prometheus / Alertmanage datasources) without any problems (apart from the unsigned property)

**Comment by getjack** [comment]
I can confirm that Grafan 7.2.x won't load the plugin as well even with the unsigned property set. I does not even appear in the UI and still says unsigned in the logs :(

**Comment by sbueringer** [comment]
@getjack So they are enforcing the signing starting with 7.2? (I assume it worked for you with e.g. 7.0.*, we're using it currently with 7.0.5)

**Comment by getjack** [comment]
@getjack I am sorry that was cleary a fault on my side. I did not write the grafana.ini configuration. After adding the line again and saving it, the plugin would appear after a service restart. It was also possible to add the data source so no problems with Grafana 7.2.0 so far - that is with version 0.1.5 of the plugin.

**Comment by sbueringer** [comment]
@getjack @igorid70 @BusterZr I published a new (signed) version of the plugin: https://grafana.com/grafana/plugins/sbueringer-consul-datasource

**Comment by linoecarrillo** [comment]
@sbueringer Hello! I tried using v0.2.1 of the plugin on Grafana 7.0.4 and I'm still seeing the issue:

```
from: https://grafana.com/api/plugins/sbueringer-consul-datasource/versions/0.2.1/download
--
into: /var/lib/grafana/plugins
✔ Installed sbueringer-consul-datasource successfully
...
t=2020-12-14T23:43:20+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"sbueringer-consul-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/sbueringer-consul-datasource/dist
--
t=2020-12-14T23:43:20+0000 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"sbueringer-consul-datasource\" is unsigned]"
```

**Comment by sbueringer** [comment]
I think you have to use Grafana 7.3.*

**Comment by linoecarrillo** [comment]
Seems like it still doesn't work for me on latest Grafana (7.3.5):

```
installing sbueringer-consul-datasource @ 0.2.1
--
from: https://grafana.com/api/plugins/sbueringer-consul-datasource/versions/0.2.1/download
into: /var/lib/grafana/plugins
✔ Installed sbueringer-consul-datasource successfully
Restart grafana after installing plugins . <service grafana-server restart>
--
t=2020-12-16T01:30:37+0000 lvl=info msg="Starting Grafana" logger=server version=7.3.5 commit=11f305f88a branch=HEAD compiled=2020-12-09T16:02:57+0000
...
t=2020-12-16T01:30:37+0000 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"sbueringer-consul-datasource\" is unsigned]"
```

This is how I'm specifying the plugin on the docker container:

```
...
grafana:
    image: grafana/grafana:7.3.5
    environment:
      - GF_INSTALL_PLUGINS=sbueringer-consul-datasource 0.2.1
...
```

**Comment by sbueringer** [comment]
@linoecarrillo To be honest, no idea how this happens. I'm trying to reproduce it with:

```
docker run --rm -it -p 3000:3000 --name=grafana --net=host  -e "GF_INSTALL_PLUGINS=sbueringer-consul-datasource 0.2.1" grafana/grafana:7.3.5
...
WARNING: Published ports are discarded when using host network mode
installing sbueringer-consul-datasource @ 0.2.1
from: https://grafana.com/api/plugins/sbueringer-consul-datasource/versions/0.2.1/download
into: /var/lib/grafana/plugins

✔ Installed sbueringer-consul-datasource successfully
...
INFO[12-16|06:37:26] Registering plugin                       logger=plugins id=input
INFO[12-16|06:37:26] Registering plugin                       logger=plugins id=sbueringer-consul-datasource
```

![Uploading image.png…]()

**Comment by linoecarrillo** [comment]
@sbueringer I'm able to run the plugin (signed!) now after I re-launched the container after commenting out the docker volume that was mounted at /var/lib/grafana. Seems like it even after installing 0.2.1, it was still trying to load 0.1.5 that was previously installed. I currently don't have a use case for that docker volume so I'm just happy to get this working for now. Thanks!

**Comment by linoecarrillo** [comment]
@sbueringer Yup! Able to reproduce my issue when I do the following:

1. `docker run --rm -it -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=sbueringer-consul-datasource 0.1.5" -v /some/host/path:/var/lib/grafana grafana/grafana:7.3.5`
1. Ctrl+C out of the container
1. `docker run --rm -it -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=sbueringer-consul-datasource 0.2.1" -v /some/host/path:/var/lib/grafana grafana/grafana:7.3.5`

Afterwards, I remove the `plugins/sbueringer-consul-datasource` directory inside the bind-mounted volume, run step 3 again and it is then able load the 0.2.1 plugin. This would be a Grafana bug eh?

**Comment by sbueringer** [comment]
@linoecarrillo I would assume. Not sure what their intended behaviour is in cases like this.
At least a plugin doesn't have influence on how Grafana does this.
